extends Node

const NAME_JUEGO_SEGUIR_LA_LINEA = "SEGUIR LA LINEA"
const NAME_JUEGO_EMPAREJAR_LAS_SOMBRAS = "EMPAREJAR LAS SOMBRAS"
const NAME_JUEGO_GIMNASIO = "GIMNASIO"
const NAME_JUEGO_BINGO_AUDITIVO = "BINGO AUDITIVO"
const NAME_JUEGO_FLECHA_Y_REACCIONA = "FLECHA Y REACCIONA"

const GENERIC_PATH = "http://79.72.62.250:8081/"
const ENDPOINT_LOG_IN = GENERIC_PATH + "auth/login"
const ENDPOINT_GET_ALL_RESIDENTS = GENERIC_PATH + "resi/resident/getAll"
const ENDPOINT_GET_ALL_GAMES = GENERIC_PATH + "resi/juego/getAll"
const ENDPOINT_POST_GAME_STATS = GENERIC_PATH + "resi/registro/juego/%d/add"
